ALTER TABLE rules DROP CONSTRAINT IF EXISTS rules_mode_check;
ALTER TABLE alerts DROP CONSTRAINT IF EXISTS alerts_mode_check;
ALTER TABLE rules DROP COLUMN IF EXISTS mode;
ALTER TABLE alerts DROP COLUMN IF EXISTS mode;
