// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===========================================================================
// Enums
// ===========================================================================
type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED EntityType = 0
	EntityType_ENTITY_TYPE_ASSET       EntityType = 1
	EntityType_ENTITY_TYPE_INSTRUMENT  EntityType = 2
	EntityType_ENTITY_TYPE_FLOW        EntityType = 3
	EntityType_ENTITY_TYPE_INSTITUTION EntityType = 4
	EntityType_ENTITY_TYPE_INDICATOR   EntityType = 5
	EntityType_ENTITY_TYPE_INDEX       EntityType = 6
	EntityType_ENTITY_TYPE_MARKET      EntityType = 7
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "ENTITY_TYPE_ASSET",
		2: "ENTITY_TYPE_INSTRUMENT",
		3: "ENTITY_TYPE_FLOW",
		4: "ENTITY_TYPE_INSTITUTION",
		5: "ENTITY_TYPE_INDICATOR",
		6: "ENTITY_TYPE_INDEX",
		7: "ENTITY_TYPE_MARKET",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED": 0,
		"ENTITY_TYPE_ASSET":       1,
		"ENTITY_TYPE_INSTRUMENT":  2,
		"ENTITY_TYPE_FLOW":        3,
		"ENTITY_TYPE_INSTITUTION": 4,
		"ENTITY_TYPE_INDICATOR":   5,
		"ENTITY_TYPE_INDEX":       6,
		"ENTITY_TYPE_MARKET":      7,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type RelationLayer int32

const (
	RelationLayer_RELATION_LAYER_UNSPECIFIED RelationLayer = 0
	RelationLayer_RELATION_LAYER_STRUCTURAL  RelationLayer = 1
	RelationLayer_RELATION_LAYER_SEMANTIC    RelationLayer = 2
	RelationLayer_RELATION_LAYER_STATISTICAL RelationLayer = 3
	RelationLayer_RELATION_LAYER_CAUSAL      RelationLayer = 4
)

// Enum value maps for RelationLayer.
var (
	RelationLayer_name = map[int32]string{
		0: "RELATION_LAYER_UNSPECIFIED",
		1: "RELATION_LAYER_STRUCTURAL",
		2: "RELATION_LAYER_SEMANTIC",
		3: "RELATION_LAYER_STATISTICAL",
		4: "RELATION_LAYER_CAUSAL",
	}
	RelationLayer_value = map[string]int32{
		"RELATION_LAYER_UNSPECIFIED": 0,
		"RELATION_LAYER_STRUCTURAL":  1,
		"RELATION_LAYER_SEMANTIC":    2,
		"RELATION_LAYER_STATISTICAL": 3,
		"RELATION_LAYER_CAUSAL":      4,
	}
)

func (x RelationLayer) Enum() *RelationLayer {
	p := new(RelationLayer)
	*p = x
	return p
}

func (x RelationLayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationLayer) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (RelationLayer) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[1]
}

func (x RelationLayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationLayer.Descriptor instead.
func (RelationLayer) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED   Direction = 0
	Direction_DIRECTION_FORWARD       Direction = 1
	Direction_DIRECTION_BACKWARD      Direction = 2
	Direction_DIRECTION_BIDIRECTIONAL Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_FORWARD",
		2: "DIRECTION_BACKWARD",
		3: "DIRECTION_BIDIRECTIONAL",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED":   0,
		"DIRECTION_FORWARD":       1,
		"DIRECTION_BACKWARD":      2,
		"DIRECTION_BIDIRECTIONAL": 3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[2]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_CRITICAL    Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_INFO        Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_CRITICAL",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_INFO",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_CRITICAL":    1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_INFO":        3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[3].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[3]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

type QualityGrade int32

const (
	QualityGrade_QUALITY_GRADE_UNSPECIFIED QualityGrade = 0
	QualityGrade_QUALITY_GRADE_REALTIME    QualityGrade = 1
	QualityGrade_QUALITY_GRADE_DELAYED     QualityGrade = 2
	QualityGrade_QUALITY_GRADE_ESTIMATED   QualityGrade = 3
	QualityGrade_QUALITY_GRADE_PRELIMINARY QualityGrade = 4
	QualityGrade_QUALITY_GRADE_REVISED     QualityGrade = 5
)

// Enum value maps for QualityGrade.
var (
	QualityGrade_name = map[int32]string{
		0: "QUALITY_GRADE_UNSPECIFIED",
		1: "QUALITY_GRADE_REALTIME",
		2: "QUALITY_GRADE_DELAYED",
		3: "QUALITY_GRADE_ESTIMATED",
		4: "QUALITY_GRADE_PRELIMINARY",
		5: "QUALITY_GRADE_REVISED",
	}
	QualityGrade_value = map[string]int32{
		"QUALITY_GRADE_UNSPECIFIED": 0,
		"QUALITY_GRADE_REALTIME":    1,
		"QUALITY_GRADE_DELAYED":     2,
		"QUALITY_GRADE_ESTIMATED":   3,
		"QUALITY_GRADE_PRELIMINARY": 4,
		"QUALITY_GRADE_REVISED":     5,
	}
)

func (x QualityGrade) Enum() *QualityGrade {
	p := new(QualityGrade)
	*p = x
	return p
}

func (x QualityGrade) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QualityGrade) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[4].Descriptor()
}

func (QualityGrade) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[4]
}

func (x QualityGrade) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QualityGrade.Descriptor instead.
func (QualityGrade) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

// Domain: Observation.source_class
type SourceClass int32

const (
	SourceClass_SOURCE_CLASS_UNSPECIFIED SourceClass = 0
	SourceClass_SOURCE_CLASS_REAL        SourceClass = 1
	SourceClass_SOURCE_CLASS_MOCK        SourceClass = 2
	SourceClass_SOURCE_CLASS_TEST        SourceClass = 3
)

// Enum value maps for SourceClass.
var (
	SourceClass_name = map[int32]string{
		0: "SOURCE_CLASS_UNSPECIFIED",
		1: "SOURCE_CLASS_REAL",
		2: "SOURCE_CLASS_MOCK",
		3: "SOURCE_CLASS_TEST",
	}
	SourceClass_value = map[string]int32{
		"SOURCE_CLASS_UNSPECIFIED": 0,
		"SOURCE_CLASS_REAL":        1,
		"SOURCE_CLASS_MOCK":        2,
		"SOURCE_CLASS_TEST":        3,
	}
)

func (x SourceClass) Enum() *SourceClass {
	p := new(SourceClass)
	*p = x
	return p
}

func (x SourceClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceClass) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_plugin_proto_enumTypes[5].Descriptor()
}

func (SourceClass) Type() protoreflect.EnumType {
	return &file_plugin_v1_plugin_proto_enumTypes[5]
}

func (x SourceClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceClass.Descriptor instead.
func (SourceClass) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

// ===========================================================================
// Registration
// ===========================================================================
type PluginInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version                string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CollectionIntervalSecs int32                  `protobuf:"varint,4,opt,name=collection_interval_secs,json=collectionIntervalSecs,proto3" json:"collection_interval_secs,omitempty"`
	MinBackfillWindowDays  int32                  `protobuf:"varint,5,opt,name=min_backfill_window_days,json=minBackfillWindowDays,proto3" json:"min_backfill_window_days,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetCollectionIntervalSecs() int32 {
	if x != nil {
		return x.CollectionIntervalSecs
	}
	return 0
}

func (x *PluginInfo) GetMinBackfillWindowDays() int32 {
	if x != nil {
		return x.MinBackfillWindowDays
	}
	return 0
}

type EntityDeclaration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	EntityType    EntityType             `protobuf:"varint,4,opt,name=entity_type,json=entityType,proto3,enum=sonde.plugin.v1.EntityType" json:"entity_type,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDeclaration) Reset() {
	*x = EntityDeclaration{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDeclaration) ProtoMessage() {}

func (x *EntityDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDeclaration.ProtoReflect.Descriptor instead.
func (*EntityDeclaration) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *EntityDeclaration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityDeclaration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityDeclaration) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EntityDeclaration) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_TYPE_UNSPECIFIED
}

func (x *EntityDeclaration) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EntityDeclaration) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetricDeclaration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Frequency     string                 `protobuf:"bytes,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	EntityId      string                 `protobuf:"bytes,6,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDeclaration) Reset() {
	*x = MetricDeclaration{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDeclaration) ProtoMessage() {}

func (x *MetricDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDeclaration.ProtoReflect.Descriptor instead.
func (*MetricDeclaration) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *MetricDeclaration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricDeclaration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricDeclaration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricDeclaration) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricDeclaration) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *MetricDeclaration) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *MetricDeclaration) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RelationSuggestion struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceId            string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId            string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	RelationType        string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Direction           Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=sonde.plugin.v1.Direction" json:"direction,omitempty"`
	Confidence          float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	TypicalLagSecs      int64                  `protobuf:"varint,6,opt,name=typical_lag_secs,json=typicalLagSecs,proto3" json:"typical_lag_secs,omitempty"`
	Description         string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Evidence            string                 `protobuf:"bytes,8,opt,name=evidence,proto3" json:"evidence,omitempty"`
	SuggestedLayer      RelationLayer          `protobuf:"varint,10,opt,name=suggested_layer,json=suggestedLayer,proto3,enum=sonde.plugin.v1.RelationLayer" json:"suggested_layer,omitempty"`
	StatisticalEvidence *StatisticalEvidence   `protobuf:"bytes,11,opt,name=statistical_evidence,json=statisticalEvidence,proto3" json:"statistical_evidence,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RelationSuggestion) Reset() {
	*x = RelationSuggestion{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationSuggestion) ProtoMessage() {}

func (x *RelationSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationSuggestion.ProtoReflect.Descriptor instead.
func (*RelationSuggestion) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *RelationSuggestion) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *RelationSuggestion) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RelationSuggestion) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *RelationSuggestion) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *RelationSuggestion) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RelationSuggestion) GetTypicalLagSecs() int64 {
	if x != nil {
		return x.TypicalLagSecs
	}
	return 0
}

func (x *RelationSuggestion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RelationSuggestion) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *RelationSuggestion) GetSuggestedLayer() RelationLayer {
	if x != nil {
		return x.SuggestedLayer
	}
	return RelationLayer_RELATION_LAYER_UNSPECIFIED
}

func (x *RelationSuggestion) GetStatisticalEvidence() *StatisticalEvidence {
	if x != nil {
		return x.StatisticalEvidence
	}
	return nil
}

type StatisticalEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	WindowDays    int32                  `protobuf:"varint,2,opt,name=window_days,json=windowDays,proto3" json:"window_days,omitempty"`
	Coefficient   float64                `protobuf:"fixed64,3,opt,name=coefficient,proto3" json:"coefficient,omitempty"`
	PValue        float64                `protobuf:"fixed64,4,opt,name=p_value,json=pValue,proto3" json:"p_value,omitempty"`
	SampleSize    int32                  `protobuf:"varint,5,opt,name=sample_size,json=sampleSize,proto3" json:"sample_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticalEvidence) Reset() {
	*x = StatisticalEvidence{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticalEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticalEvidence) ProtoMessage() {}

func (x *StatisticalEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticalEvidence.ProtoReflect.Descriptor instead.
func (*StatisticalEvidence) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *StatisticalEvidence) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StatisticalEvidence) GetWindowDays() int32 {
	if x != nil {
		return x.WindowDays
	}
	return 0
}

func (x *StatisticalEvidence) GetCoefficient() float64 {
	if x != nil {
		return x.Coefficient
	}
	return 0
}

func (x *StatisticalEvidence) GetPValue() float64 {
	if x != nil {
		return x.PValue
	}
	return 0
}

func (x *StatisticalEvidence) GetSampleSize() int32 {
	if x != nil {
		return x.SampleSize
	}
	return 0
}

type RelationReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	RelationType  string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Decision      string                 `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	MergedInto    *RelationSuggestion    `protobuf:"bytes,6,opt,name=merged_into,json=mergedInto,proto3" json:"merged_into,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationReview) Reset() {
	*x = RelationReview{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationReview) ProtoMessage() {}

func (x *RelationReview) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationReview.ProtoReflect.Descriptor instead.
func (*RelationReview) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *RelationReview) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *RelationReview) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RelationReview) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *RelationReview) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *RelationReview) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RelationReview) GetMergedInto() *RelationSuggestion {
	if x != nil {
		return x.MergedInto
	}
	return nil
}

type RuleSuggestion struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MetricId     string                 `protobuf:"bytes,2,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	DetectorName string                 `protobuf:"bytes,3,opt,name=detector_name,json=detectorName,proto3" json:"detector_name,omitempty"`
	Severity     Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=sonde.plugin.v1.Severity" json:"severity,omitempty"`
	Config       []byte                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Description  string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Domain: Rule.display_name — UI label. Empty means fall back to name (slug).
	DisplayName   string `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSuggestion) Reset() {
	*x = RuleSuggestion{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSuggestion) ProtoMessage() {}

func (x *RuleSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSuggestion.ProtoReflect.Descriptor instead.
func (*RuleSuggestion) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *RuleSuggestion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleSuggestion) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *RuleSuggestion) GetDetectorName() string {
	if x != nil {
		return x.DetectorName
	}
	return ""
}

func (x *RuleSuggestion) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *RuleSuggestion) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RuleSuggestion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuleSuggestion) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RuleReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleReview) Reset() {
	*x = RuleReview{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleReview) ProtoMessage() {}

func (x *RuleReview) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleReview.ProtoReflect.Descriptor instead.
func (*RuleReview) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *RuleReview) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleReview) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *RuleReview) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Domain: Plugin.capabilities — declared topology, not inferred by type assert.
type PluginCapabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WindowedBackfill bool                   `protobuf:"varint,1,opt,name=windowed_backfill,json=windowedBackfill,proto3" json:"windowed_backfill,omitempty"`
	MaxBackfillDays  int32                  `protobuf:"varint,2,opt,name=max_backfill_days,json=maxBackfillDays,proto3" json:"max_backfill_days,omitempty"`
	RequiresSecrets  []string               `protobuf:"bytes,3,rep,name=requires_secrets,json=requiresSecrets,proto3" json:"requires_secrets,omitempty"`
	MockAvailable    bool                   `protobuf:"varint,4,opt,name=mock_available,json=mockAvailable,proto3" json:"mock_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginCapabilities) Reset() {
	*x = PluginCapabilities{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCapabilities) ProtoMessage() {}

func (x *PluginCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCapabilities.ProtoReflect.Descriptor instead.
func (*PluginCapabilities) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PluginCapabilities) GetWindowedBackfill() bool {
	if x != nil {
		return x.WindowedBackfill
	}
	return false
}

func (x *PluginCapabilities) GetMaxBackfillDays() int32 {
	if x != nil {
		return x.MaxBackfillDays
	}
	return 0
}

func (x *PluginCapabilities) GetRequiresSecrets() []string {
	if x != nil {
		return x.RequiresSecrets
	}
	return nil
}

func (x *PluginCapabilities) GetMockAvailable() bool {
	if x != nil {
		return x.MockAvailable
	}
	return false
}

type RegisterPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PluginInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Entities      []*EntityDeclaration   `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Relations     []*RelationSuggestion  `protobuf:"bytes,3,rep,name=relations,proto3" json:"relations,omitempty"`
	Metrics       []*MetricDeclaration   `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Rules         []*RuleSuggestion      `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	ChangeLog     string                 `protobuf:"bytes,10,opt,name=change_log,json=changeLog,proto3" json:"change_log,omitempty"`
	Capabilities  *PluginCapabilities    `protobuf:"bytes,11,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPluginRequest) Reset() {
	*x = RegisterPluginRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginRequest) ProtoMessage() {}

func (x *RegisterPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPluginRequest.ProtoReflect.Descriptor instead.
func (*RegisterPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterPluginRequest) GetInfo() *PluginInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *RegisterPluginRequest) GetEntities() []*EntityDeclaration {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *RegisterPluginRequest) GetRelations() []*RelationSuggestion {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *RegisterPluginRequest) GetMetrics() []*MetricDeclaration {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *RegisterPluginRequest) GetRules() []*RuleSuggestion {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *RegisterPluginRequest) GetChangeLog() string {
	if x != nil {
		return x.ChangeLog
	}
	return ""
}

func (x *RegisterPluginRequest) GetCapabilities() *PluginCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterPluginResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PluginId            string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	RegistrationVersion int32                  `protobuf:"varint,2,opt,name=registration_version,json=registrationVersion,proto3" json:"registration_version,omitempty"`
	Success             bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ReviewedRelations   []*RelationReview      `protobuf:"bytes,5,rep,name=reviewed_relations,json=reviewedRelations,proto3" json:"reviewed_relations,omitempty"`
	ReviewedRules       []*RuleReview          `protobuf:"bytes,6,rep,name=reviewed_rules,json=reviewedRules,proto3" json:"reviewed_rules,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterPluginResponse) Reset() {
	*x = RegisterPluginResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginResponse) ProtoMessage() {}

func (x *RegisterPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPluginResponse.ProtoReflect.Descriptor instead.
func (*RegisterPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterPluginResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RegisterPluginResponse) GetRegistrationVersion() int32 {
	if x != nil {
		return x.RegistrationVersion
	}
	return 0
}

func (x *RegisterPluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterPluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterPluginResponse) GetReviewedRelations() []*RelationReview {
	if x != nil {
		return x.ReviewedRelations
	}
	return nil
}

func (x *RegisterPluginResponse) GetReviewedRules() []*RuleReview {
	if x != nil {
		return x.ReviewedRules
	}
	return nil
}

// ===========================================================================
// Data Push
// ===========================================================================
type MetricSnapshot struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MetricId            string                 `protobuf:"bytes,1,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	Value               float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp           int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels              map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SourcePlugin        string                 `protobuf:"bytes,5,opt,name=source_plugin,json=sourcePlugin,proto3" json:"source_plugin,omitempty"`
	SourcePluginVersion string                 `protobuf:"bytes,6,opt,name=source_plugin_version,json=sourcePluginVersion,proto3" json:"source_plugin_version,omitempty"`
	SourceProvider      string                 `protobuf:"bytes,7,opt,name=source_provider,json=sourceProvider,proto3" json:"source_provider,omitempty"`
	SourceFetchedAt     int64                  `protobuf:"varint,8,opt,name=source_fetched_at,json=sourceFetchedAt,proto3" json:"source_fetched_at,omitempty"`
	QualityGrade        QualityGrade           `protobuf:"varint,9,opt,name=quality_grade,json=qualityGrade,proto3,enum=sonde.plugin.v1.QualityGrade" json:"quality_grade,omitempty"`
	QualityConfidence   float64                `protobuf:"fixed64,10,opt,name=quality_confidence,json=qualityConfidence,proto3" json:"quality_confidence,omitempty"`
	// Domain: Observation.source_class. Absent/zero means unknown.
	SourceClass   SourceClass `protobuf:"varint,11,opt,name=source_class,json=sourceClass,proto3,enum=sonde.plugin.v1.SourceClass" json:"source_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSnapshot) Reset() {
	*x = MetricSnapshot{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSnapshot) ProtoMessage() {}

func (x *MetricSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSnapshot.ProtoReflect.Descriptor instead.
func (*MetricSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *MetricSnapshot) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *MetricSnapshot) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricSnapshot) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricSnapshot) GetSourcePlugin() string {
	if x != nil {
		return x.SourcePlugin
	}
	return ""
}

func (x *MetricSnapshot) GetSourcePluginVersion() string {
	if x != nil {
		return x.SourcePluginVersion
	}
	return ""
}

func (x *MetricSnapshot) GetSourceProvider() string {
	if x != nil {
		return x.SourceProvider
	}
	return ""
}

func (x *MetricSnapshot) GetSourceFetchedAt() int64 {
	if x != nil {
		return x.SourceFetchedAt
	}
	return 0
}

func (x *MetricSnapshot) GetQualityGrade() QualityGrade {
	if x != nil {
		return x.QualityGrade
	}
	return QualityGrade_QUALITY_GRADE_UNSPECIFIED
}

func (x *MetricSnapshot) GetQualityConfidence() float64 {
	if x != nil {
		return x.QualityConfidence
	}
	return 0
}

func (x *MetricSnapshot) GetSourceClass() SourceClass {
	if x != nil {
		return x.SourceClass
	}
	return SourceClass_SOURCE_CLASS_UNSPECIFIED
}

type PushSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Snapshots     []*MetricSnapshot      `protobuf:"bytes,2,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSnapshotsRequest) Reset() {
	*x = PushSnapshotsRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSnapshotsRequest) ProtoMessage() {}

func (x *PushSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*PushSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *PushSnapshotsRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PushSnapshotsRequest) GetSnapshots() []*MetricSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type PushSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Inserted      int32                  `protobuf:"varint,2,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Deduplicated  int32                  `protobuf:"varint,3,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	Rejected      int32                  `protobuf:"varint,4,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSnapshotsResponse) Reset() {
	*x = PushSnapshotsResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSnapshotsResponse) ProtoMessage() {}

func (x *PushSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*PushSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *PushSnapshotsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushSnapshotsResponse) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *PushSnapshotsResponse) GetDeduplicated() int32 {
	if x != nil {
		return x.Deduplicated
	}
	return 0
}

func (x *PushSnapshotsResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *PushSnapshotsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ===========================================================================
// Heartbeat
// ===========================================================================
type PluginStatus struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	State                 string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	LastCollectAt         int64                  `protobuf:"varint,2,opt,name=last_collect_at,json=lastCollectAt,proto3" json:"last_collect_at,omitempty"`
	LastCollectDurationMs int32                  `protobuf:"varint,3,opt,name=last_collect_duration_ms,json=lastCollectDurationMs,proto3" json:"last_collect_duration_ms,omitempty"`
	LastCollectCount      int32                  `protobuf:"varint,4,opt,name=last_collect_count,json=lastCollectCount,proto3" json:"last_collect_count,omitempty"`
	LastCollectError      string                 `protobuf:"bytes,5,opt,name=last_collect_error,json=lastCollectError,proto3" json:"last_collect_error,omitempty"`
	ConsecutiveErrors     int32                  `protobuf:"varint,6,opt,name=consecutive_errors,json=consecutiveErrors,proto3" json:"consecutive_errors,omitempty"`
	Runtime               map[string]string      `protobuf:"bytes,7,rep,name=runtime,proto3" json:"runtime,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *PluginStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PluginStatus) GetLastCollectAt() int64 {
	if x != nil {
		return x.LastCollectAt
	}
	return 0
}

func (x *PluginStatus) GetLastCollectDurationMs() int32 {
	if x != nil {
		return x.LastCollectDurationMs
	}
	return 0
}

func (x *PluginStatus) GetLastCollectCount() int32 {
	if x != nil {
		return x.LastCollectCount
	}
	return 0
}

func (x *PluginStatus) GetLastCollectError() string {
	if x != nil {
		return x.LastCollectError
	}
	return ""
}

func (x *PluginStatus) GetConsecutiveErrors() int32 {
	if x != nil {
		return x.ConsecutiveErrors
	}
	return 0
}

func (x *PluginStatus) GetRuntime() map[string]string {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        *PluginStatus          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() *PluginStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ok                bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	HasPendingCommand bool                   `protobuf:"varint,2,opt,name=has_pending_command,json=hasPendingCommand,proto3" json:"has_pending_command,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetHasPendingCommand() bool {
	if x != nil {
		return x.HasPendingCommand
	}
	return false
}

// ===========================================================================
// Commands
// ===========================================================================
type SyncCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	MetricIds     []string               `protobuf:"bytes,3,rep,name=metric_ids,json=metricIds,proto3" json:"metric_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCommand) Reset() {
	*x = SyncCommand{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCommand) ProtoMessage() {}

func (x *SyncCommand) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCommand.ProtoReflect.Descriptor instead.
func (*SyncCommand) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *SyncCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SyncCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SyncCommand) GetMetricIds() []string {
	if x != nil {
		return x.MetricIds
	}
	return nil
}

type BackfillCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	WindowStart   int64                  `protobuf:"varint,3,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd     int64                  `protobuf:"varint,4,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	MetricIds     []string               `protobuf:"bytes,5,rep,name=metric_ids,json=metricIds,proto3" json:"metric_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillCommand) Reset() {
	*x = BackfillCommand{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillCommand) ProtoMessage() {}

func (x *BackfillCommand) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillCommand.ProtoReflect.Descriptor instead.
func (*BackfillCommand) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *BackfillCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *BackfillCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BackfillCommand) GetWindowStart() int64 {
	if x != nil {
		return x.WindowStart
	}
	return 0
}

func (x *BackfillCommand) GetWindowEnd() int64 {
	if x != nil {
		return x.WindowEnd
	}
	return 0
}

func (x *BackfillCommand) GetMetricIds() []string {
	if x != nil {
		return x.MetricIds
	}
	return nil
}

type CommandAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CollectedCount int32                  `protobuf:"varint,5,opt,name=collected_count,json=collectedCount,proto3" json:"collected_count,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CommandAck) GetCollectedCount() int32 {
	if x != nil {
		return x.CollectedCount
	}
	return 0
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ===========================================================================
// Bidirectional Stream Messages
// ===========================================================================
type PluginMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PluginMessage_PushSnapshots
	//	*PluginMessage_Heartbeat
	//	*PluginMessage_CommandAck
	Payload       isPluginMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *PluginMessage) GetPayload() isPluginMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PluginMessage) GetPushSnapshots() *PushSnapshotsRequest {
	if x != nil {
		if x, ok := x.Payload.(*PluginMessage_PushSnapshots); ok {
			return x.PushSnapshots
		}
	}
	return nil
}

func (x *PluginMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*PluginMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *PluginMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*PluginMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

type isPluginMessage_Payload interface {
	isPluginMessage_Payload()
}

type PluginMessage_PushSnapshots struct {
	PushSnapshots *PushSnapshotsRequest `protobuf:"bytes,1,opt,name=push_snapshots,json=pushSnapshots,proto3,oneof"`
}

type PluginMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type PluginMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,3,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

func (*PluginMessage_PushSnapshots) isPluginMessage_Payload() {}

func (*PluginMessage_Heartbeat) isPluginMessage_Payload() {}

func (*PluginMessage_CommandAck) isPluginMessage_Payload() {}

type CoreMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoreMessage_Sync
	//	*CoreMessage_Backfill
	//	*CoreMessage_PushAck
	Payload       isCoreMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreMessage) Reset() {
	*x = CoreMessage{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreMessage) ProtoMessage() {}

func (x *CoreMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreMessage.ProtoReflect.Descriptor instead.
func (*CoreMessage) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *CoreMessage) GetPayload() isCoreMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoreMessage) GetSync() *SyncCommand {
	if x != nil {
		if x, ok := x.Payload.(*CoreMessage_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

func (x *CoreMessage) GetBackfill() *BackfillCommand {
	if x != nil {
		if x, ok := x.Payload.(*CoreMessage_Backfill); ok {
			return x.Backfill
		}
	}
	return nil
}

func (x *CoreMessage) GetPushAck() *PushAck {
	if x != nil {
		if x, ok := x.Payload.(*CoreMessage_PushAck); ok {
			return x.PushAck
		}
	}
	return nil
}

type isCoreMessage_Payload interface {
	isCoreMessage_Payload()
}

type CoreMessage_Sync struct {
	Sync *SyncCommand `protobuf:"bytes,1,opt,name=sync,proto3,oneof"`
}

type CoreMessage_Backfill struct {
	Backfill *BackfillCommand `protobuf:"bytes,2,opt,name=backfill,proto3,oneof"`
}

type CoreMessage_PushAck struct {
	PushAck *PushAck `protobuf:"bytes,3,opt,name=push_ack,json=pushAck,proto3,oneof"` // M1: ack for stream push (ADR-9)
}

func (*CoreMessage_Sync) isCoreMessage_Payload() {}

func (*CoreMessage_Backfill) isCoreMessage_Payload() {}

func (*CoreMessage_PushAck) isCoreMessage_Payload() {}

type PushAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Inserted      int32                  `protobuf:"varint,2,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Deduplicated  int32                  `protobuf:"varint,3,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	Rejected      int32                  `protobuf:"varint,4,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *PushAck) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PushAck) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *PushAck) GetDeduplicated() int32 {
	if x != nil {
		return x.Deduplicated
	}
	return 0
}

func (x *PushAck) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *PushAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\x0fsonde.plugin.v1\"\xcf\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x128\n" +
	"\x18collection_interval_secs\x18\x04 \x01(\x05R\x16collectionIntervalSecs\x127\n" +
	"\x18min_backfill_window_days\x18\x05 \x01(\x05R\x15minBackfillWindowDays\"\xb2\x02\n" +
	"\x11EntityDeclaration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12<\n" +
	"\ventity_type\x18\x04 \x01(\x0e2\x1b.sonde.plugin.v1.EntityTypeR\n" +
	"entityType\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12L\n" +
	"\bmetadata\x18\x06 \x03(\v20.sonde.plugin.v1.EntityDeclaration.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x02\n" +
	"\x11MetricDeclaration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\tR\tfrequency\x12\x1b\n" +
	"\tentity_id\x18\x06 \x01(\tR\bentityId\x12@\n" +
	"\x04tags\x18\a \x03(\v2,.sonde.plugin.v1.MetricDeclaration.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x03\n" +
	"\x12RelationSuggestion\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\x128\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x1a.sonde.plugin.v1.DirectionR\tdirection\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12(\n" +
	"\x10typical_lag_secs\x18\x06 \x01(\x03R\x0etypicalLagSecs\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1a\n" +
	"\bevidence\x18\b \x01(\tR\bevidence\x12G\n" +
	"\x0fsuggested_layer\x18\n" +
	" \x01(\x0e2\x1e.sonde.plugin.v1.RelationLayerR\x0esuggestedLayer\x12W\n" +
	"\x14statistical_evidence\x18\v \x01(\v2$.sonde.plugin.v1.StatisticalEvidenceR\x13statisticalEvidence\"\xaa\x01\n" +
	"\x13StatisticalEvidence\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1f\n" +
	"\vwindow_days\x18\x02 \x01(\x05R\n" +
	"windowDays\x12 \n" +
	"\vcoefficient\x18\x03 \x01(\x01R\vcoefficient\x12\x17\n" +
	"\ap_value\x18\x04 \x01(\x01R\x06pValue\x12\x1f\n" +
	"\vsample_size\x18\x05 \x01(\x05R\n" +
	"sampleSize\"\xe9\x01\n" +
	"\x0eRelationReview\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\x12\x1a\n" +
	"\bdecision\x18\x04 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12D\n" +
	"\vmerged_into\x18\x06 \x01(\v2#.sonde.plugin.v1.RelationSuggestionR\n" +
	"mergedInto\"\xfa\x01\n" +
	"\x0eRuleSuggestion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmetric_id\x18\x02 \x01(\tR\bmetricId\x12#\n" +
	"\rdetector_name\x18\x03 \x01(\tR\fdetectorName\x125\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x19.sonde.plugin.v1.SeverityR\bseverity\x12\x16\n" +
	"\x06config\x18\x05 \x01(\fR\x06config\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\"T\n" +
	"\n" +
	"RuleReview\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xbf\x01\n" +
	"\x12PluginCapabilities\x12+\n" +
	"\x11windowed_backfill\x18\x01 \x01(\bR\x10windowedBackfill\x12*\n" +
	"\x11max_backfill_days\x18\x02 \x01(\x05R\x0fmaxBackfillDays\x12)\n" +
	"\x10requires_secrets\x18\x03 \x03(\tR\x0frequiresSecrets\x12%\n" +
	"\x0emock_available\x18\x04 \x01(\bR\rmockAvailable\"\xa8\x03\n" +
	"\x15RegisterPluginRequest\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.sonde.plugin.v1.PluginInfoR\x04info\x12>\n" +
	"\bentities\x18\x02 \x03(\v2\".sonde.plugin.v1.EntityDeclarationR\bentities\x12A\n" +
	"\trelations\x18\x03 \x03(\v2#.sonde.plugin.v1.RelationSuggestionR\trelations\x12<\n" +
	"\ametrics\x18\x04 \x03(\v2\".sonde.plugin.v1.MetricDeclarationR\ametrics\x125\n" +
	"\x05rules\x18\x05 \x03(\v2\x1f.sonde.plugin.v1.RuleSuggestionR\x05rules\x12\x1d\n" +
	"\n" +
	"change_log\x18\n" +
	" \x01(\tR\tchangeLog\x12G\n" +
	"\fcapabilities\x18\v \x01(\v2#.sonde.plugin.v1.PluginCapabilitiesR\fcapabilities\"\xb0\x02\n" +
	"\x16RegisterPluginResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x121\n" +
	"\x14registration_version\x18\x02 \x01(\x05R\x13registrationVersion\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12N\n" +
	"\x12reviewed_relations\x18\x05 \x03(\v2\x1f.sonde.plugin.v1.RelationReviewR\x11reviewedRelations\x12B\n" +
	"\x0ereviewed_rules\x18\x06 \x03(\v2\x1b.sonde.plugin.v1.RuleReviewR\rreviewedRules\"\xc3\x04\n" +
	"\x0eMetricSnapshot\x12\x1b\n" +
	"\tmetric_id\x18\x01 \x01(\tR\bmetricId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12C\n" +
	"\x06labels\x18\x04 \x03(\v2+.sonde.plugin.v1.MetricSnapshot.LabelsEntryR\x06labels\x12#\n" +
	"\rsource_plugin\x18\x05 \x01(\tR\fsourcePlugin\x122\n" +
	"\x15source_plugin_version\x18\x06 \x01(\tR\x13sourcePluginVersion\x12'\n" +
	"\x0fsource_provider\x18\a \x01(\tR\x0esourceProvider\x12*\n" +
	"\x11source_fetched_at\x18\b \x01(\x03R\x0fsourceFetchedAt\x12B\n" +
	"\rquality_grade\x18\t \x01(\x0e2\x1d.sonde.plugin.v1.QualityGradeR\fqualityGrade\x12-\n" +
	"\x12quality_confidence\x18\n" +
	" \x01(\x01R\x11qualityConfidence\x12?\n" +
	"\fsource_class\x18\v \x01(\x0e2\x1c.sonde.plugin.v1.SourceClassR\vsourceClass\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x14PushSnapshotsRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12=\n" +
	"\tsnapshots\x18\x02 \x03(\v2\x1f.sonde.plugin.v1.MetricSnapshotR\tsnapshots\"\xa7\x01\n" +
	"\x15PushSnapshotsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\binserted\x18\x02 \x01(\x05R\binserted\x12\"\n" +
	"\fdeduplicated\x18\x03 \x01(\x05R\fdeduplicated\x12\x1a\n" +
	"\brejected\x18\x04 \x01(\x05R\brejected\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x92\x03\n" +
	"\fPluginStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12&\n" +
	"\x0flast_collect_at\x18\x02 \x01(\x03R\rlastCollectAt\x127\n" +
	"\x18last_collect_duration_ms\x18\x03 \x01(\x05R\x15lastCollectDurationMs\x12,\n" +
	"\x12last_collect_count\x18\x04 \x01(\x05R\x10lastCollectCount\x12,\n" +
	"\x12last_collect_error\x18\x05 \x01(\tR\x10lastCollectError\x12-\n" +
	"\x12consecutive_errors\x18\x06 \x01(\x05R\x11consecutiveErrors\x12D\n" +
	"\aruntime\x18\a \x03(\v2*.sonde.plugin.v1.PluginStatus.RuntimeEntryR\aruntime\x1a:\n" +
	"\fRuntimeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x125\n" +
	"\x06status\x18\x03 \x01(\v2\x1d.sonde.plugin.v1.PluginStatusR\x06status\"S\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12.\n" +
	"\x13has_pending_command\x18\x02 \x01(\bR\x11hasPendingCommand\"c\n" +
	"\vSyncCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"metric_ids\x18\x03 \x03(\tR\tmetricIds\"\xa9\x01\n" +
	"\x0fBackfillCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fwindow_start\x18\x03 \x01(\x03R\vwindowStart\x12\x1d\n" +
	"\n" +
	"window_end\x18\x04 \x01(\x03R\twindowEnd\x12\x1d\n" +
	"\n" +
	"metric_ids\x18\x05 \x03(\tR\tmetricIds\"\xba\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fcollected_count\x18\x05 \x01(\x05R\x0ecollectedCount\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xed\x01\n" +
	"\rPluginMessage\x12N\n" +
	"\x0epush_snapshots\x18\x01 \x01(\v2%.sonde.plugin.v1.PushSnapshotsRequestH\x00R\rpushSnapshots\x12A\n" +
	"\theartbeat\x18\x02 \x01(\v2!.sonde.plugin.v1.HeartbeatRequestH\x00R\theartbeat\x12>\n" +
	"\vcommand_ack\x18\x03 \x01(\v2\x1b.sonde.plugin.v1.CommandAckH\x00R\n" +
	"commandAckB\t\n" +
	"\apayload\"\xc3\x01\n" +
	"\vCoreMessage\x122\n" +
	"\x04sync\x18\x01 \x01(\v2\x1c.sonde.plugin.v1.SyncCommandH\x00R\x04sync\x12>\n" +
	"\bbackfill\x18\x02 \x01(\v2 .sonde.plugin.v1.BackfillCommandH\x00R\bbackfill\x125\n" +
	"\bpush_ack\x18\x03 \x01(\v2\x18.sonde.plugin.v1.PushAckH\x00R\apushAckB\t\n" +
	"\apayload\"\x9c\x01\n" +
	"\aPushAck\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1a\n" +
	"\binserted\x18\x02 \x01(\x05R\binserted\x12\"\n" +
	"\fdeduplicated\x18\x03 \x01(\x05R\fdeduplicated\x12\x1a\n" +
	"\brejected\x18\x04 \x01(\x05R\brejected\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*\xd9\x01\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ENTITY_TYPE_ASSET\x10\x01\x12\x1a\n" +
	"\x16ENTITY_TYPE_INSTRUMENT\x10\x02\x12\x14\n" +
	"\x10ENTITY_TYPE_FLOW\x10\x03\x12\x1b\n" +
	"\x17ENTITY_TYPE_INSTITUTION\x10\x04\x12\x19\n" +
	"\x15ENTITY_TYPE_INDICATOR\x10\x05\x12\x15\n" +
	"\x11ENTITY_TYPE_INDEX\x10\x06\x12\x16\n" +
	"\x12ENTITY_TYPE_MARKET\x10\a*\xa6\x01\n" +
	"\rRelationLayer\x12\x1e\n" +
	"\x1aRELATION_LAYER_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RELATION_LAYER_STRUCTURAL\x10\x01\x12\x1b\n" +
	"\x17RELATION_LAYER_SEMANTIC\x10\x02\x12\x1e\n" +
	"\x1aRELATION_LAYER_STATISTICAL\x10\x03\x12\x19\n" +
	"\x15RELATION_LAYER_CAUSAL\x10\x04*r\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECTION_FORWARD\x10\x01\x12\x16\n" +
	"\x12DIRECTION_BACKWARD\x10\x02\x12\x1b\n" +
	"\x17DIRECTION_BIDIRECTIONAL\x10\x03*d\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x03*\xbb\x01\n" +
	"\fQualityGrade\x12\x1d\n" +
	"\x19QUALITY_GRADE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16QUALITY_GRADE_REALTIME\x10\x01\x12\x19\n" +
	"\x15QUALITY_GRADE_DELAYED\x10\x02\x12\x1b\n" +
	"\x17QUALITY_GRADE_ESTIMATED\x10\x03\x12\x1d\n" +
	"\x19QUALITY_GRADE_PRELIMINARY\x10\x04\x12\x19\n" +
	"\x15QUALITY_GRADE_REVISED\x10\x05*p\n" +
	"\vSourceClass\x12\x1c\n" +
	"\x18SOURCE_CLASS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SOURCE_CLASS_REAL\x10\x01\x12\x15\n" +
	"\x11SOURCE_CLASS_MOCK\x10\x02\x12\x15\n" +
	"\x11SOURCE_CLASS_TEST\x10\x032\x98\x02\n" +
	"\n" +
	"PluginHost\x12a\n" +
	"\x0eRegisterPlugin\x12&.sonde.plugin.v1.RegisterPluginRequest\x1a'.sonde.plugin.v1.RegisterPluginResponse\x12S\n" +
	"\x0fMaintainSession\x12\x1e.sonde.plugin.v1.PluginMessage\x1a\x1c.sonde.plugin.v1.CoreMessage(\x010\x01\x12R\n" +
	"\tHeartbeat\x12!.sonde.plugin.v1.HeartbeatRequest\x1a\".sonde.plugin.v1.HeartbeatResponseB$Z\"sonde/pkg/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(EntityType)(0),                // 0: sonde.plugin.v1.EntityType
	(RelationLayer)(0),             // 1: sonde.plugin.v1.RelationLayer
	(Direction)(0),                 // 2: sonde.plugin.v1.Direction
	(Severity)(0),                  // 3: sonde.plugin.v1.Severity
	(QualityGrade)(0),              // 4: sonde.plugin.v1.QualityGrade
	(SourceClass)(0),               // 5: sonde.plugin.v1.SourceClass
	(*PluginInfo)(nil),             // 6: sonde.plugin.v1.PluginInfo
	(*EntityDeclaration)(nil),      // 7: sonde.plugin.v1.EntityDeclaration
	(*MetricDeclaration)(nil),      // 8: sonde.plugin.v1.MetricDeclaration
	(*RelationSuggestion)(nil),     // 9: sonde.plugin.v1.RelationSuggestion
	(*StatisticalEvidence)(nil),    // 10: sonde.plugin.v1.StatisticalEvidence
	(*RelationReview)(nil),         // 11: sonde.plugin.v1.RelationReview
	(*RuleSuggestion)(nil),         // 12: sonde.plugin.v1.RuleSuggestion
	(*RuleReview)(nil),             // 13: sonde.plugin.v1.RuleReview
	(*PluginCapabilities)(nil),     // 14: sonde.plugin.v1.PluginCapabilities
	(*RegisterPluginRequest)(nil),  // 15: sonde.plugin.v1.RegisterPluginRequest
	(*RegisterPluginResponse)(nil), // 16: sonde.plugin.v1.RegisterPluginResponse
	(*MetricSnapshot)(nil),         // 17: sonde.plugin.v1.MetricSnapshot
	(*PushSnapshotsRequest)(nil),   // 18: sonde.plugin.v1.PushSnapshotsRequest
	(*PushSnapshotsResponse)(nil),  // 19: sonde.plugin.v1.PushSnapshotsResponse
	(*PluginStatus)(nil),           // 20: sonde.plugin.v1.PluginStatus
	(*HeartbeatRequest)(nil),       // 21: sonde.plugin.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 22: sonde.plugin.v1.HeartbeatResponse
	(*SyncCommand)(nil),            // 23: sonde.plugin.v1.SyncCommand
	(*BackfillCommand)(nil),        // 24: sonde.plugin.v1.BackfillCommand
	(*CommandAck)(nil),             // 25: sonde.plugin.v1.CommandAck
	(*PluginMessage)(nil),          // 26: sonde.plugin.v1.PluginMessage
	(*CoreMessage)(nil),            // 27: sonde.plugin.v1.CoreMessage
	(*PushAck)(nil),                // 28: sonde.plugin.v1.PushAck
	nil,                            // 29: sonde.plugin.v1.EntityDeclaration.MetadataEntry
	nil,                            // 30: sonde.plugin.v1.MetricDeclaration.TagsEntry
	nil,                            // 31: sonde.plugin.v1.MetricSnapshot.LabelsEntry
	nil,                            // 32: sonde.plugin.v1.PluginStatus.RuntimeEntry
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	0,  // 0: sonde.plugin.v1.EntityDeclaration.entity_type:type_name -> sonde.plugin.v1.EntityType
	29, // 1: sonde.plugin.v1.EntityDeclaration.metadata:type_name -> sonde.plugin.v1.EntityDeclaration.MetadataEntry
	30, // 2: sonde.plugin.v1.MetricDeclaration.tags:type_name -> sonde.plugin.v1.MetricDeclaration.TagsEntry
	2,  // 3: sonde.plugin.v1.RelationSuggestion.direction:type_name -> sonde.plugin.v1.Direction
	1,  // 4: sonde.plugin.v1.RelationSuggestion.suggested_layer:type_name -> sonde.plugin.v1.RelationLayer
	10, // 5: sonde.plugin.v1.RelationSuggestion.statistical_evidence:type_name -> sonde.plugin.v1.StatisticalEvidence
	9,  // 6: sonde.plugin.v1.RelationReview.merged_into:type_name -> sonde.plugin.v1.RelationSuggestion
	3,  // 7: sonde.plugin.v1.RuleSuggestion.severity:type_name -> sonde.plugin.v1.Severity
	6,  // 8: sonde.plugin.v1.RegisterPluginRequest.info:type_name -> sonde.plugin.v1.PluginInfo
	7,  // 9: sonde.plugin.v1.RegisterPluginRequest.entities:type_name -> sonde.plugin.v1.EntityDeclaration
	9,  // 10: sonde.plugin.v1.RegisterPluginRequest.relations:type_name -> sonde.plugin.v1.RelationSuggestion
	8,  // 11: sonde.plugin.v1.RegisterPluginRequest.metrics:type_name -> sonde.plugin.v1.MetricDeclaration
	12, // 12: sonde.plugin.v1.RegisterPluginRequest.rules:type_name -> sonde.plugin.v1.RuleSuggestion
	14, // 13: sonde.plugin.v1.RegisterPluginRequest.capabilities:type_name -> sonde.plugin.v1.PluginCapabilities
	11, // 14: sonde.plugin.v1.RegisterPluginResponse.reviewed_relations:type_name -> sonde.plugin.v1.RelationReview
	13, // 15: sonde.plugin.v1.RegisterPluginResponse.reviewed_rules:type_name -> sonde.plugin.v1.RuleReview
	31, // 16: sonde.plugin.v1.MetricSnapshot.labels:type_name -> sonde.plugin.v1.MetricSnapshot.LabelsEntry
	4,  // 17: sonde.plugin.v1.MetricSnapshot.quality_grade:type_name -> sonde.plugin.v1.QualityGrade
	5,  // 18: sonde.plugin.v1.MetricSnapshot.source_class:type_name -> sonde.plugin.v1.SourceClass
	17, // 19: sonde.plugin.v1.PushSnapshotsRequest.snapshots:type_name -> sonde.plugin.v1.MetricSnapshot
	32, // 20: sonde.plugin.v1.PluginStatus.runtime:type_name -> sonde.plugin.v1.PluginStatus.RuntimeEntry
	20, // 21: sonde.plugin.v1.HeartbeatRequest.status:type_name -> sonde.plugin.v1.PluginStatus
	18, // 22: sonde.plugin.v1.PluginMessage.push_snapshots:type_name -> sonde.plugin.v1.PushSnapshotsRequest
	21, // 23: sonde.plugin.v1.PluginMessage.heartbeat:type_name -> sonde.plugin.v1.HeartbeatRequest
	25, // 24: sonde.plugin.v1.PluginMessage.command_ack:type_name -> sonde.plugin.v1.CommandAck
	23, // 25: sonde.plugin.v1.CoreMessage.sync:type_name -> sonde.plugin.v1.SyncCommand
	24, // 26: sonde.plugin.v1.CoreMessage.backfill:type_name -> sonde.plugin.v1.BackfillCommand
	28, // 27: sonde.plugin.v1.CoreMessage.push_ack:type_name -> sonde.plugin.v1.PushAck
	15, // 28: sonde.plugin.v1.PluginHost.RegisterPlugin:input_type -> sonde.plugin.v1.RegisterPluginRequest
	26, // 29: sonde.plugin.v1.PluginHost.MaintainSession:input_type -> sonde.plugin.v1.PluginMessage
	21, // 30: sonde.plugin.v1.PluginHost.Heartbeat:input_type -> sonde.plugin.v1.HeartbeatRequest
	16, // 31: sonde.plugin.v1.PluginHost.RegisterPlugin:output_type -> sonde.plugin.v1.RegisterPluginResponse
	27, // 32: sonde.plugin.v1.PluginHost.MaintainSession:output_type -> sonde.plugin.v1.CoreMessage
	22, // 33: sonde.plugin.v1.PluginHost.Heartbeat:output_type -> sonde.plugin.v1.HeartbeatResponse
	31, // [31:34] is the sub-list for method output_type
	28, // [28:31] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	file_plugin_v1_plugin_proto_msgTypes[20].OneofWrappers = []any{
		(*PluginMessage_PushSnapshots)(nil),
		(*PluginMessage_Heartbeat)(nil),
		(*PluginMessage_CommandAck)(nil),
	}
	file_plugin_v1_plugin_proto_msgTypes[21].OneofWrappers = []any{
		(*CoreMessage_Sync)(nil),
		(*CoreMessage_Backfill)(nil),
		(*CoreMessage_PushAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
