// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PluginHost_RegisterPlugin_FullMethodName  = "/capital_observatory.plugin.v1.PluginHost/RegisterPlugin"
	PluginHost_MaintainSession_FullMethodName = "/capital_observatory.plugin.v1.PluginHost/MaintainSession"
	PluginHost_Heartbeat_FullMethodName       = "/capital_observatory.plugin.v1.PluginHost/Heartbeat"
)

// PluginHostClient is the client API for PluginHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===========================================================================
// PluginHost — Core exposes this service to Plugins
// ===========================================================================
type PluginHostClient interface {
	RegisterPlugin(ctx context.Context, in *RegisterPluginRequest, opts ...grpc.CallOption) (*RegisterPluginResponse, error)
	MaintainSession(ctx context.Context, opts ...grpc.CallOption) (PluginHost_MaintainSessionClient, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type pluginHostClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHostClient(cc grpc.ClientConnInterface) PluginHostClient {
	return &pluginHostClient{cc}
}

func (c *pluginHostClient) RegisterPlugin(ctx context.Context, in *RegisterPluginRequest, opts ...grpc.CallOption) (*RegisterPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPluginResponse)
	err := c.cc.Invoke(ctx, PluginHost_RegisterPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) MaintainSession(ctx context.Context, opts ...grpc.CallOption) (PluginHost_MaintainSessionClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginHost_ServiceDesc.Streams[0], PluginHost_MaintainSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &pluginHostMaintainSessionClient{ClientStream: stream}
	return x, nil
}

type PluginHost_MaintainSessionClient interface {
	Send(*PluginMessage) error
	Recv() (*CoreMessage, error)
	grpc.ClientStream
}

type pluginHostMaintainSessionClient struct {
	grpc.ClientStream
}

func (x *pluginHostMaintainSessionClient) Send(m *PluginMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pluginHostMaintainSessionClient) Recv() (*CoreMessage, error) {
	m := new(CoreMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pluginHostClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, PluginHost_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginHostServer is the server API for PluginHost service.
// All implementations must embed UnimplementedPluginHostServer
// for forward compatibility
//
// ===========================================================================
// PluginHost — Core exposes this service to Plugins
// ===========================================================================
type PluginHostServer interface {
	RegisterPlugin(context.Context, *RegisterPluginRequest) (*RegisterPluginResponse, error)
	MaintainSession(PluginHost_MaintainSessionServer) error
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedPluginHostServer()
}

// UnimplementedPluginHostServer must be embedded to have forward compatible implementations.
type UnimplementedPluginHostServer struct {
}

func (UnimplementedPluginHostServer) RegisterPlugin(context.Context, *RegisterPluginRequest) (*RegisterPluginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPlugin not implemented")
}
func (UnimplementedPluginHostServer) MaintainSession(PluginHost_MaintainSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method MaintainSession not implemented")
}
func (UnimplementedPluginHostServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPluginHostServer) mustEmbedUnimplementedPluginHostServer() {}

// UnsafePluginHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHostServer will
// result in compilation errors.
type UnsafePluginHostServer interface {
	mustEmbedUnimplementedPluginHostServer()
}

func RegisterPluginHostServer(s grpc.ServiceRegistrar, srv PluginHostServer) {
	s.RegisterService(&PluginHost_ServiceDesc, srv)
}

func _PluginHost_RegisterPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).RegisterPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_RegisterPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).RegisterPlugin(ctx, req.(*RegisterPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_MaintainSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginHostServer).MaintainSession(&pluginHostMaintainSessionServer{ServerStream: stream})
}

type PluginHost_MaintainSessionServer interface {
	Send(*CoreMessage) error
	Recv() (*PluginMessage, error)
	grpc.ServerStream
}

type pluginHostMaintainSessionServer struct {
	grpc.ServerStream
}

func (x *pluginHostMaintainSessionServer) Send(m *CoreMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pluginHostMaintainSessionServer) Recv() (*PluginMessage, error) {
	m := new(PluginMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PluginHost_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginHost_ServiceDesc is the grpc.ServiceDesc for PluginHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capital_observatory.plugin.v1.PluginHost",
	HandlerType: (*PluginHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPlugin",
			Handler:    _PluginHost_RegisterPlugin_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _PluginHost_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MaintainSession",
			Handler:       _PluginHost_MaintainSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin/v1/plugin.proto",
}
